### PR TITLE
Update cisagov_I.yml

### PR DESCRIPTION
**Pull request by inl-ics**
Added Ivanti vendor products

#  #

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - _eschew scope creep!_
- [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

### CODE REVIEW

**Comment by justmurphy** [comment]
@inl-ics Hey guys, hope you're doing well.  You made changes to the Ivanti products (cisagov_I.yml) in PR #443, and then here it is changing some of those updates.  For instance, PR #443 changed the version numbers for the Ivanti Avalanche product to affected versions '6.2.2' and '6.3.0 to 6.3.3'.  This PR (#444) changes the Avalanche product to unaffected.  Should I go with the updates from this PR (#444), or keep the ones from PR #443?  Just want to make sure we have the correct information in the table. Thanks :)

**Comment by inl-ics** [comment]
Please use the later one (444), thank you

**Comment by justmurphy** [comment]
@inl-ics Got ya, we will get it updated soon.

**Review by justmurphy — APPROVED** [review]
Thanks for the updates.

**Pull request merged**
