### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by inl-ics**
Added Baxter, HOLOGIC, and BBraun (was already there, added products and a working advisory link).

#  #

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - _eschew scope creep!_
- [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

### CODE REVIEW

**Comment by justmurphy** [comment]
@inl-ics is there a reason for removing the Lyrasis entry?  That was submitted by different contributor?

**Comment by inl-ics** [comment]
I never performed this action, wasn't even working in the L's, which is interesting that is shows that this account removed something.

**Review by justmurphy — CHANGES_REQUESTED** [review]
Sorry to ask, but could you update your branch and resubmit PR? @inl-ics

**Comment by inl-ics** [comment]
This is all confusing to me, I am not sure what has happened, or if someone has been also editing in this account. The Lyrasis shouldn't have been removed. This was originally created as a fork and not a branch. Things seem to be stuck at the moment and I am not proficient enough in GitHub to get things fixed.

**Comment by justmurphy** [comment]
@inl-ics No worries.  We will go ahead and push this through, and I will re-add the Lyrasis entry.

**Review by justmurphy — APPROVED** [review]
Thank you.

**Comment by inl-ics** [comment]
thank you, I'll keep an eye out going forward if anything I didn't touch is marked for removal, and see if I can find out why, or at least revert before making a push request.

**Pull request merged**
