### PR TITLE
Update cisagov_B.yml

### PR DESCRIPTION
**Pull request by inl-ics**
Updated BBraun status, updated Beckman Coulter

#  #

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - _eschew scope creep!_
- [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

### CODE REVIEW

**Comment by inl-ics** [comment]
Not sure what I need to fix, the details just say Error: Process completed with exit code 1. Hopefully you can see more of where the issue is. Thanks

**Comment by justmurphy** [comment]
@inl-ics it says something about a trailing white space.  I tried a quick search and could not find it.
image

I will take a more in depth look here shortly

**Comment by justmurphy** [comment]
@inl-ics found it on line 1130, after the date. Should be good now

**Review by justmurphy — APPROVED** [review]
Thank you!

**Comment by inl-ics** [comment]
thank you

**Pull request merged**
