### PR TITLE
Update SOFTWARE-LIST.md

### PR DESCRIPTION
**Pull request by danielhartnell**
#  #

## 🗣 Description ##

* Adds missing Amazon AWS services
* Adds PagerDuty SaaS
* Updates Tenable product statement

## 💭 Motivation and context ##

We investigated these services and wanted to contribute our findings.

## 🧪 Testing ##

I setup and ran `pre-commit` per the contributions document. 

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] Changes are limited to a single goal - _eschew scope creep!_
- [X] All relevant type-of-change labels have been added.
- [X] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.

## ✅ Pre-merge checklist ##

Let me know if anything should be added here.

## ✅ Post-merge checklist ##

Let me know if anything should be added here.

### CODE REVIEW

**Comment by mrshorten** [comment]
I have a few applications that need to be added to the list. My company maintains these applications. How do I get additions added. It is not letting me create a pull for Software List

**Comment by danielhartnell** [comment]
> I have a few applications that need to be added to the list. My company maintains these applications. How do I get additions added. It is not letting me create a pull for Software List

@mrshorten,

I'm not sure why you were unable to create a pull request. The only thing I can think of doing is review the [documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) for creating one. Sorry if that's giving you information you already have. I'm just a contributor so I can't speak on behalf of the cisagov team. Good luck!

**Comment by justmurphy** [comment]
@mrshorten same guidance from us.  Should be no restrictions in place.  Thank you @danielhartnell for providing documentation.

**Review by justmurphy — APPROVED** [review]
Thank you for the submission

**Comment by danielhartnell** [comment]
> Thank you for the submission

Cheers! Thanks for maintaining this.

**Pull request merged**
