### PR TITLE
Updated Salesforce statuses

### PR DESCRIPTION
**Pull request by CodeAlligator**
Updated Salesforce

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - _eschew scope creep!_
- [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

### CODE REVIEW

**Review by justmurphy — APPROVED** [review]
Thank you for the updates.

**Comment by CodeAlligator** [comment]
@justmurphy Thank you for the PR merge. Do I need to update the software-list.md file as well or will that get auto-populated by the GitHub Action? I noticed software-list.md doesn't reflect this change so checking.

**Comment by justmurphy** [comment]
@CodeAlligator Should be auto-populated.  It appears to be on my end https://github.com/cisagov/log4j-affected-db/blob/develop/SOFTWARE-LIST.md

**Comment by CodeAlligator** [comment]
@justmurphy ok thank you

**Pull request merged**
