### PR TITLE
Oracle, SAP and other minor updates

### PR DESCRIPTION
**Pull request by zmanion**
Oracle and SAP details are only available to customers, making risk assessment much more difficult.

### CODE REVIEW

**Comment by zmanion** [comment]
@justindmurphy try this in place of #205 .

**Comment by justmurphy** [comment]
@zmanion can you give us maintainer editing ability when you submit the PR.  We need to update the branch with base branch and have ability to resolve merge conflicts.  No problem with your update, we just do not want to erase data from other updates.

**Comment by zmanion** [comment]
@justmurphy Will do (Allow edits from maintainers), IIUC I can't modify this PR because it came from certcc (an organizational account), I don't see the option anywhere.

So will submit from a personal/user account next time.

I can close this and try from my zmanion account, or just grab the SAP and Oracle edits and make them directly? Also SonicWall Email Security was material, other changes were formatting/moving data to what I think is the correct column.

**Comment by zmanion** [comment]
> @justmurphy Will do (Allow edits from maintainers), IIUC I can't modify this PR because it came from certcc (an organizational account), I don't see the option anywhere.

I've given you @justmurphy write access to the certcc fork, which might give you the ability to edit. Lmk.

**Review by justmurphy — APPROVED** [review]
Should be good now, thanks @zmanion

**Pull request merged**
