### PR TITLE
Add information about JetBrains products

### PR DESCRIPTION
**Pull request by dingo15**
## ✅ Checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by dingo15** [comment]
Hi team, could you please update information about the JetBrains products? We'll be happy to provide any additional details if needed.

**Review by justmurphy — CHANGES_REQUESTED** [review]
Could you update the pull requests for the first two entries (lines 1056 & 1057).  Tests are rejecting the formatting and not able to merge.
README.md:1056:225 MD010/no-hard-tabs Hard tabs [Column: 225]
README.md:1057:128 MD010/no-hard-tabs Hard tabs [Column: 128]

**Comment by dingo15** [comment]
@justmurphy I've dropped the tabs, seems to be fine now.
Thanks!

**Comment by justmurphy** [comment]
@dingo15 thanks for the changes.  Updating now.  Appreciate the help.

**Review by justmurphy — APPROVED** [review]
Thank you

**Pull request merged**
