### PR TITLE
Oracle, SAP, SonicWall ES, editorial

### PR DESCRIPTION
**Pull request by zmanion**

### CODE REVIEW

**Review by justmurphy — CHANGES_REQUESTED** [review]
Art, it says on our end that your branch is out of date with the base branch.  Could you update on your side and resubmit the pull request.

**Comment by justmurphy** [comment]
I think it might be the html elements \<p\> in the Oracle entry... might be the case for the others too.

**Comment by zmanion** [comment]
Removed \<p\> tags, it may be me but I didn't see any useful output from lint. Have a new PR ready and can close this and file new as the next option.

**Review by justmurphy — APPROVED** [review]

**Review by justmurphy — CHANGES_REQUESTED** [review]
Art, formatting changes removing p tags fixed... still says out of date with base branch.. How about we close this one and go the new submission route?

**Comment by zmanion** [comment]
@justmurphy see #246.

**Pull request closed without merging**
